environment:
  HERITAGE: generator-mono-serverless:package
  SLS_AWS_STAGE: ${env:SLS_AWS_STAGE, 'dev'}
  SLS_AWS_REGION: ${env:SLS_AWS_REGION, 'ap-southeast-2'}
  SLS_APIGW_ENDPOINT_TYPE: ${env:SLS_APIGW_ENDPOINT_TYPE, 'EDGE'}
<% if (snsErrorTopicArn) { -%>
  SLS_SNS_ERROR_TOPIC_ARN: ${env:SLS_SNS_ERROR_TOPIC_ARN}
<% } -%>
<% if (deploymentBucketPrefix) { -%>
  SLS_DEPLOYMENT_S3_BUCKET_PREFIX: ${env:SLS_DEPLOYMENT_S3_BUCKET_PREFIX}
<% } -%>
<% if (kmsEncryptionKeyIdBucket) { -%>
  SLS_DEPLOYMENT_BUCKET_KMS_KEY_ID: ${env:SLS_DEPLOYMENT_BUCKET_KMS_KEY_ID}
<% } -%>
<% if (kmsEncryptionKeyId) { -%>
  SLS_AWS_KMS_KEY_ID: ${env:SLS_AWS_KMS_KEY_ID}
<% } -%>
<% if (executionAwsRole) { -%>
  SLS_AWS_EXECUTION_ROLE: ${env:SLS_AWS_EXECUTION_ROLE}
<% } -%>
<% if (s3EventBucket) { -%>
  SLS_AWS_S3_EVENT_BUCKET: ${env:SLS_AWS_S3_EVENT_BUCKET}
  SLS_AWS_S3_EVENT_TRIGGER: ${env:SLS_AWS_S3_EVENT_TRIGGER}
<% } -%>
<% if (ddbTableName) { -%>
  SLS_DYNAMODB_TABLENAME: ${env:SLS_DYNAMODB_TABLENAME}
<% } -%>
<% if (apiGatewayAuthorizer) { -%>
  SLS_AWS_API_AUTHORIZER: ${env:SLS_AWS_API_AUTHORIZER}
<% } -%>
<% if (useVpc) { -%>
  SLS_VPC_ID: ${env:SLS_VPC_ID}
  SLS_VPC_SECURITY_GROUP_ID: ${env:SLS_VPC_SECURITY_GROUP_ID}
  SLS_VPC_SUBNET_A: ${env:SLS_VPC_SUBNET_A}
  SLS_VPC_SUBNET_B: ${env:SLS_VPC_SUBNET_B}
  SLS_VPC_SUBNET_C: ${env:SLS_VPC_SUBNET_C}
<% } -%>
